# Generated by Django 5.0.7 on 2024-08-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_chat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mmessages",
                to="chat.chat",
            ),
        ),
    ]
