# Generated by Django 5.0.7 on 2024-08-14 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_message_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="users_online",
            field=models.ManyToManyField(
                related_name="online",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи онлайн",
            ),
        ),
    ]
